name: Fetch Card to Repo

on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change dir
        run: cd burndown
      - name: Run fetch
        run: docker compose up --build
      - name: Check result
        run: ls -la data