name: Fetch Card to Repo

on:  
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions: read-all
      
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        env: 
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run fetch
        run: docker compose up --build
        working-directory: ./burndown
      - name: Check result
        run: ls -la data
        working-directory: ./burndown
        # Enable tmate debugging of manually-triggered workflows if the input option was provided