name: Fetch Card to Repo

on:  
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
            envkey_GITHUB_TOKEN: ${{ secrets.BURNDOWN_GITHUB_TOKEN }}
            envkey_PROJECT_ID: ${{ secrets.BURNDOWN_PROJECT_ID }}
            directory: ./burndown
            file_name: .env
            fail_on_empty: false
      - name: Run fetch
        run: docker compose up --build
        working-directory: ./burndown
      - name: Check result
        run: ls -la data
        working-directory: ./burndown
      - name: Commit report
        run: |
          git add .
          git config --global user.name 'workflow'
          git config --global user.email 'workflow@users.noreply.github.com'
          git commit -am "Automated report"
          git push
        # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}