version: '3.9'
services:
  burndown:
    image: burndown:local
    build:
      context: .
      dockerfile: .Dockerfile
    platform: linux/amd64
    command: pipenv run python3 main.py
    volumes:
      - ./app:/src/app
      - ./data:/src/data
      - venv:/src/app/.venv
      - vscode-server:/root/.vscode-server
    env_file:
      - .env
volumes:
  vscode-server:
  venv: