version: '3.9'
services:
  burndown:
    image: burndown:local
    build:
      context: .
      dockerfile: .Dockerfile
    platform: linux/amd64
    volumes:
      - ./app:/src/app
      - venv:/src/app/.venv
      - vscode-server:/root/.vscode-server
    env_file:
      - .env
volumes:
  vscode-server:
  venv: